language: node_js
node_js:
  - 16

services:
  - docker

before_install:
  - docker build -t martintrajanovski/docker-react -f Dockerfile.dev .

script:
  - docker run martintrajanovski/docker-react npm run test -- --watchAll=false
