language: node_js
node_js:
  - 16

services:
  - docker

before_install:
  - docker build -t martintrajanovski/docker-react -f Dockerfile.dev .

script:
  - docker run martintrajanovski/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-eu-north-1-806178707623
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
